name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main   # change if your deployment branch is different

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"      # root folder with your index.html
          skip_app_build: true   # skip Node/React build
          output_location: "."   # deploy files as-is
          action: "upload"
